spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baltaragis_api?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

# MySQL-specific configuration
app:
  base-url: http://localhost:8080
  payments:
    enabled: true
  rate-limit:
    enabled: true
    capacity: 10
    window-minutes: 5