logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:dev-migration
  h2:
    console:
      enabled: true
      path: /h2-console
  # MailHog configuration for development
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Development-specific configuration
app:
  # Use localhost for development sitemap
  base-url: http://localhost:8080
  payments:
    enabled: true
  # Rate limiting configuration (more lenient for dev)
  rate-limit:
    enabled: true
    capacity: 10
    window-minutes: 5


