spring:
  application:
    name: BaltaragisAPI
  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

# Media storage configuration
app:
  media:
    base-path: media
    base-url: http://localhost:8080/media


