spring:
  application:
    name: BaltaragisAPI
  profiles:
    active: dev
  # Email configuration (can be overridden by environment variables)
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:false}
          starttls:
            enable: ${SMTP_STARTTLS:false}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

# Application configuration
app:
  # Base URL for sitemap generation
  base-url: ${BASE_URL:https://www.baltaragis.com}
  # Media storage configuration
  media:
    base-path: media
    base-url: http://localhost:8080/media
  # Payment configuration
  payments:
    enabled: ${PAYMENTS_ENABLED:false}
  # Rate limiting configuration (production defaults)
  rate-limit:
    enabled: true
    capacity: 5
    window-minutes: 5


